// export const SALOON_SIGNUP_REQUEST="SALOON_SIGNUP_REQUEST"
// export const SALOON_SIGNUP_SUCCESS="SALOON_SIGNUP_SUCCESS"
// export const SALOON_SIGNUP_FAIL    ="SALOON_SIGNUP_FAIL"

// export const BRANCH_SIGNUP_REQUEST="BRANCH_SIGNUP_REQUEST"
// export const BRANCH_SIGNUP_SUCCESS="BRANCH_SIGNUP_SUCCESS"
// export const BRANCH_SIGNUP_FAIL="BRANCH_SIGNUP_FAIL"